version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
  migrate-db:
    build: .
    command: ["make", "prepdb"]
    env_file:
      - ./django_project/.env
    depends_on:
      - web
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./django_project/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
